package com.vn.gcs.serp.model;
// Generated Jul 28, 2016 7:43:01 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuotationDetails generated by hbm2java
 */
@Entity
@Table(name = "quotation_details", catalog = "serp_qtdh")
public class QuotationDetails implements java.io.Serializable {

	private Integer quotationDetailsId;
	private Quotations quotations;
	private String nameOfDetail;
	private Integer quantity;
	private String unit;
	private Double price;
	private Double amount;
	private String note;

	public QuotationDetails() {
	}

	public QuotationDetails(Quotations quotations) {
		this.quotations = quotations;
	}

	public QuotationDetails(Quotations quotations, String nameOfDetail, Integer quantity, String unit, Double price,
			Double amount, String note) {
		this.quotations = quotations;
		this.nameOfDetail = nameOfDetail;
		this.quantity = quantity;
		this.unit = unit;
		this.price = price;
		this.amount = amount;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "QuotationDetailsID", unique = true, nullable = false)
	public Integer getQuotationDetailsId() {
		return this.quotationDetailsId;
	}

	public void setQuotationDetailsId(Integer quotationDetailsId) {
		this.quotationDetailsId = quotationDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QuotationId", nullable = false)
	public Quotations getQuotations() {
		return this.quotations;
	}

	public void setQuotations(Quotations quotations) {
		this.quotations = quotations;
	}

	@Column(name = "NameOfDetail", length = 50)
	public String getNameOfDetail() {
		return this.nameOfDetail;
	}

	public void setNameOfDetail(String nameOfDetail) {
		this.nameOfDetail = nameOfDetail;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Unit", length = 50)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "Price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "Amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
