package com.gcs.serp_qtdh.model;
// Generated Jul 28, 2016 7:43:01 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estimates generated by hbm2java
 */
@Entity
@Table(name = "estimates", catalog = "serp_qtdh")
public class Estimates implements java.io.Serializable {

	private Integer id;
	private Orders orders;
	private String estimateId;
	private Date publishDate;
	private String approve;
	private String approvalContent;
	private String approver;
	private String userId;
	private Set<Quotations> quotationses = new HashSet<Quotations>(0);
	private Set<EstimateDetails> estimateDetailses = new HashSet<EstimateDetails>(0);

	public Estimates() {
	}

	public Estimates(Orders orders, String estimateId, Date publishDate, String approver, String userId) {
		this.orders = orders;
		this.estimateId = estimateId;
		this.publishDate = publishDate;
		this.approver = approver;
		this.userId = userId;
	}

	public Estimates(Orders orders, String estimateId, Date publishDate, String approve, String approvalContent,
			String approver, String userId, Set<Quotations> quotationses, Set<EstimateDetails> estimateDetailses) {
		this.orders = orders;
		this.estimateId = estimateId;
		this.publishDate = publishDate;
		this.approve = approve;
		this.approvalContent = approvalContent;
		this.approver = approver;
		this.userId = userId;
		this.quotationses = quotationses;
		this.estimateDetailses = estimateDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderId", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "EstimateID", nullable = false, length = 50)
	public String getEstimateId() {
		return this.estimateId;
	}

	public void setEstimateId(String estimateId) {
		this.estimateId = estimateId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PublishDate", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Column(name = "Approve", length = 50)
	public String getApprove() {
		return this.approve;
	}

	public void setApprove(String approve) {
		this.approve = approve;
	}

	@Column(name = "ApprovalContent", length = 65535)
	public String getApprovalContent() {
		return this.approvalContent;
	}

	public void setApprovalContent(String approvalContent) {
		this.approvalContent = approvalContent;
	}

	@Column(name = "Approver", nullable = false, length = 50)
	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	@Column(name = "UserID", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estimates")
	public Set<Quotations> getQuotationses() {
		return this.quotationses;
	}

	public void setQuotationses(Set<Quotations> quotationses) {
		this.quotationses = quotationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estimates")
	public Set<EstimateDetails> getEstimateDetailses() {
		return this.estimateDetailses;
	}

	public void setEstimateDetailses(Set<EstimateDetails> estimateDetailses) {
		this.estimateDetailses = estimateDetailses;
	}

}
