package com.gcs.serp_qtdh.model;
// Generated Jul 28, 2016 7:43:01 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ROrders generated by hbm2java
 */
@Entity
@Table(name = "r_orders", catalog = "serp_qtdh")
public class ROrders implements java.io.Serializable {

	private Integer id;
	private Orders orders;
	private String rorderId;
	private Date backupDate;
	private String projectName;
	private Date publishDate;
	private String orderContent;
	private Integer possibility;
	private String judgingContent;
	private Integer approve;
	private String approvalContent;
	private Date modifiedDate;

	public ROrders() {
	}

	public ROrders(Orders orders, String rorderId) {
		this.orders = orders;
		this.rorderId = rorderId;
	}

	public ROrders(Orders orders, String rorderId, Date backupDate, String projectName, Date publishDate,
			String orderContent, Integer possibility, String judgingContent, Integer approve, String approvalContent,
			Date modifiedDate) {
		this.orders = orders;
		this.rorderId = rorderId;
		this.backupDate = backupDate;
		this.projectName = projectName;
		this.publishDate = publishDate;
		this.orderContent = orderContent;
		this.possibility = possibility;
		this.judgingContent = judgingContent;
		this.approve = approve;
		this.approvalContent = approvalContent;
		this.modifiedDate = modifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OrderId", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "ROrderID", nullable = false, length = 50)
	public String getRorderId() {
		return this.rorderId;
	}

	public void setRorderId(String rorderId) {
		this.rorderId = rorderId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BackupDate", length = 10)
	public Date getBackupDate() {
		return this.backupDate;
	}

	public void setBackupDate(Date backupDate) {
		this.backupDate = backupDate;
	}

	@Column(name = "ProjectName", length = 100)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PublishDate", length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Column(name = "OrderContent", length = 65535)
	public String getOrderContent() {
		return this.orderContent;
	}

	public void setOrderContent(String orderContent) {
		this.orderContent = orderContent;
	}

	@Column(name = "Possibility")
	public Integer getPossibility() {
		return this.possibility;
	}

	public void setPossibility(Integer possibility) {
		this.possibility = possibility;
	}

	@Column(name = "JudgingContent", length = 65535)
	public String getJudgingContent() {
		return this.judgingContent;
	}

	public void setJudgingContent(String judgingContent) {
		this.judgingContent = judgingContent;
	}

	@Column(name = "Approve")
	public Integer getApprove() {
		return this.approve;
	}

	public void setApprove(Integer approve) {
		this.approve = approve;
	}

	@Column(name = "ApprovalContent", length = 65535)
	public String getApprovalContent() {
		return this.approvalContent;
	}

	public void setApprovalContent(String approvalContent) {
		this.approvalContent = approvalContent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ModifiedDate", length = 10)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
