package serp.model;
// Generated Jul 28, 2016 7:45:42 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstimateDetails generated by hbm2java
 */
@Entity
@Table(name = "estimate_details", catalog = "serp_qtdh")
public class EstimateDetails implements java.io.Serializable {

	private Integer estimateDetailsId;
	private Estimates estimates;
	private Products products;
	private double costMaterial;
	private int quantity;
	private Double weightMaterial;
	private String embryos;
	private Double costLabor;
	private Double costEquipment;
	private Double costTool;
	private Double costExternal;
	private Double price;
	private Double sum;

	public EstimateDetails() {
	}

	public EstimateDetails(Estimates estimates, Products products, double costMaterial, int quantity) {
		this.estimates = estimates;
		this.products = products;
		this.costMaterial = costMaterial;
		this.quantity = quantity;
	}

	public EstimateDetails(Estimates estimates, Products products, double costMaterial, int quantity,
			Double weightMaterial, String embryos, Double costLabor, Double costEquipment, Double costTool,
			Double costExternal, Double price, Double sum) {
		this.estimates = estimates;
		this.products = products;
		this.costMaterial = costMaterial;
		this.quantity = quantity;
		this.weightMaterial = weightMaterial;
		this.embryos = embryos;
		this.costLabor = costLabor;
		this.costEquipment = costEquipment;
		this.costTool = costTool;
		this.costExternal = costExternal;
		this.price = price;
		this.sum = sum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EstimateDetailsID", unique = true, nullable = false)
	public Integer getEstimateDetailsId() {
		return this.estimateDetailsId;
	}

	public void setEstimateDetailsId(Integer estimateDetailsId) {
		this.estimateDetailsId = estimateDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EstimateId", nullable = false)
	public Estimates getEstimates() {
		return this.estimates;
	}

	public void setEstimates(Estimates estimates) {
		this.estimates = estimates;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductId", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "CostMaterial", nullable = false, precision = 22, scale = 0)
	public double getCostMaterial() {
		return this.costMaterial;
	}

	public void setCostMaterial(double costMaterial) {
		this.costMaterial = costMaterial;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "WeightMaterial", precision = 22, scale = 0)
	public Double getWeightMaterial() {
		return this.weightMaterial;
	}

	public void setWeightMaterial(Double weightMaterial) {
		this.weightMaterial = weightMaterial;
	}

	@Column(name = "Embryos", length = 50)
	public String getEmbryos() {
		return this.embryos;
	}

	public void setEmbryos(String embryos) {
		this.embryos = embryos;
	}

	@Column(name = "CostLabor", precision = 22, scale = 0)
	public Double getCostLabor() {
		return this.costLabor;
	}

	public void setCostLabor(Double costLabor) {
		this.costLabor = costLabor;
	}

	@Column(name = "CostEquipment", precision = 22, scale = 0)
	public Double getCostEquipment() {
		return this.costEquipment;
	}

	public void setCostEquipment(Double costEquipment) {
		this.costEquipment = costEquipment;
	}

	@Column(name = "CostTool", precision = 22, scale = 0)
	public Double getCostTool() {
		return this.costTool;
	}

	public void setCostTool(Double costTool) {
		this.costTool = costTool;
	}

	@Column(name = "CostExternal", precision = 22, scale = 0)
	public Double getCostExternal() {
		return this.costExternal;
	}

	public void setCostExternal(Double costExternal) {
		this.costExternal = costExternal;
	}

	@Column(name = "Price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "Sum", precision = 22, scale = 0)
	public Double getSum() {
		return this.sum;
	}

	public void setSum(Double sum) {
		this.sum = sum;
	}

}
