package serp.model;
// Generated Jul 28, 2016 7:45:42 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", catalog = "serp_qtdh")
public class Products implements java.io.Serializable {

	private Integer id;
	private String productId;
	private String productName;
	private String unit;
	private Set<EstimateDetails> estimateDetailses = new HashSet<EstimateDetails>(0);
	private Set<Materials> materialses = new HashSet<Materials>(0);

	public Products() {
	}

	public Products(String productId) {
		this.productId = productId;
	}

	public Products(String productId, String productName, String unit, Set<EstimateDetails> estimateDetailses,
			Set<Materials> materialses) {
		this.productId = productId;
		this.productName = productName;
		this.unit = unit;
		this.estimateDetailses = estimateDetailses;
		this.materialses = materialses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ProductID", nullable = false, length = 50)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "ProductName", length = 45)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "Unit", length = 45)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<EstimateDetails> getEstimateDetailses() {
		return this.estimateDetailses;
	}

	public void setEstimateDetailses(Set<EstimateDetails> estimateDetailses) {
		this.estimateDetailses = estimateDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Materials> getMaterialses() {
		return this.materialses;
	}

	public void setMaterialses(Set<Materials> materialses) {
		this.materialses = materialses;
	}

}
