package com.serp.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Element generated by hbm2java
 */
@Entity
@Table(name = "element", catalog = "serp")
public class Element implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Size(min = 1, max = 50)
	@NotEmpty(message = "ID must be something")
	private String EId;
	@NotEmpty(message = "Name must be between 1 and 50 characters long")
	@Size(min = 1, max = 50)
	private String EName;
	@NotEmpty
	@Size(min = 1, max = 50)
	private String EUnit;
	private Set<LimitInventoryDetail> limitInventoryDetails = new HashSet<LimitInventoryDetail>(0);
	private Set<EstimateDetail> estimateDetails = new HashSet<EstimateDetail>(0);
	private Set<StockRequisitionDetails> stockRequisitionDetailses = new HashSet<StockRequisitionDetails>(0);

	public Element() {
	}

	public Element(String EId, String EName, String EUnit, Set<LimitInventoryDetail> limitInventoryDetails,
			Set<EstimateDetail> estimateDetails, Set<StockRequisitionDetails> stockRequisitionDetailses) {
		this.EId = EId;
		this.EName = EName;
		this.EUnit = EUnit;
		this.limitInventoryDetails = limitInventoryDetails;
		this.estimateDetails = estimateDetails;
		this.stockRequisitionDetailses = stockRequisitionDetailses;
	}

	@Override
	public String toString() {
		return "Element [EId=" + EId + ", EName=" + EName + ", EUnit=" + EUnit + "]";
	}

	@Id
	@Column(name = "e_id", unique = true, nullable = false, length = 50)
	public String getEId() {
		return this.EId;
	}

	public void setEId(String EId) {
		this.EId = EId;
	}

	@Column(name = "e_name", nullable = false, length = 200)
	public String getEName() {
		return this.EName;
	}

	public void setEName(String EName) {
		this.EName = EName;
	}

	@Column(name = "e_unit", nullable = false, length = 50)
	public String getEUnit() {
		return this.EUnit;
	}

	public void setEUnit(String EUnit) {
		this.EUnit = EUnit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "element")
	public Set<LimitInventoryDetail> getLimitInventoryDetails() {
		return this.limitInventoryDetails;
	}

	public void setLimitInventoryDetails(Set<LimitInventoryDetail> limitInventoryDetails) {
		this.limitInventoryDetails = limitInventoryDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "element")
	public Set<EstimateDetail> getEstimateDetails() {
		return this.estimateDetails;
	}

	public void setEstimateDetails(Set<EstimateDetail> estimateDetails) {
		this.estimateDetails = estimateDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "element")
	public Set<StockRequisitionDetails> getStockRequisitionDetailses() {
		return this.stockRequisitionDetailses;
	}

	public void setStockRequisitionDetailses(Set<StockRequisitionDetails> stockRequisitionDetailses) {
		this.stockRequisitionDetailses = stockRequisitionDetailses;
	}

}
