package com.serp.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;

// Generated Apr 13, 2016 8:57:22 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * EstimateDetail generated by hbm2java
 */
@Entity
@Table(name = "estimate_detail", catalog = "serp")
public class EstimateDetail implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private Integer edId;
    @NotNull
    private Element element;
    private Estimate estimate;
    @NotNull(message = "Choose.Material")
    private Material material;
    @Min(1)
    @Max(999999)
    private int edQuantity;
    @Min(0)
    @Max(999999)
    private double edMaterialWeight;
    @Min(0)
    @Max(999999)
    private double edPhi;
    @Min(0)
    @Max(999999)
    private double edX;
    @Min(0)
    @Max(999999)
    private double edY;
    @Min(0)
    @Max(999999)
    private double edZ;
    @Min(0)
    private double edMaterialCost;
    @Min(0)
    private double edLaborCost;
    @Min(0)
    private double edEquipmentCost;
    @Min(0)
    private double edToolCost;
    @Min(0)
    private double edExternalCost;
    @Min(0)
    private double edPrice;
    @Min(0)
    private double edTotalCost;

    public EstimateDetail() {
    }

    public EstimateDetail(Element element, Estimate estimate, Material material, int edQuantity,
	    double edMaterialWeight, double edPhi, double edX, double edY, double edZ, double edMaterialCost,
	    double edLaborCost, double edEquipmentCost, double edToolCost, double edExternalCost, double edPrice,
	    double edTotalCost) {
	this.element = element;
	this.estimate = estimate;
	this.material = material;
	this.edQuantity = edQuantity;
	this.edMaterialWeight = edMaterialWeight;
	this.edPhi = edPhi;
	this.edX = edX;
	this.edY = edY;
	this.edZ = edZ;
	this.edMaterialCost = edMaterialCost;
	this.edLaborCost = edLaborCost;
	this.edEquipmentCost = edEquipmentCost;
	this.edToolCost = edToolCost;
	this.edExternalCost = edExternalCost;
	this.edPrice = edPrice;
	this.edTotalCost = edTotalCost;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ed_id", unique = true, nullable = false)
    public Integer getEdId() {
	return this.edId;
    }

    public void setEdId(Integer edId) {
	this.edId = edId;
    }

    @ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name = "ed_element_id", nullable = false)
    public Element getElement() {
	return this.element;
    }

    public void setElement(Element element) {
	this.element = element;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ed_material_id", nullable = false)
    public Material getMaterial() {
	return this.material;
    }

    public void setMaterial(Material material) {
	this.material = material;
    }

    @Column(name = "ed_quantity", nullable = false)
    public int getEdQuantity() {
	return this.edQuantity;
    }

    public void setEdQuantity(int edQuantity) {
	this.edQuantity = edQuantity;
    }

    @Column(name = "ed_material_weight", nullable = false, precision = 22, scale = 0)
    public double getEdMaterialWeight() {
	return this.edMaterialWeight;
    }

    public void setEdMaterialWeight(double edMaterialWeight) {
	this.edMaterialWeight = edMaterialWeight;
    }

    @Column(name = "ed_phi", nullable = false, precision = 22, scale = 0)
    public double getEdPhi() {
	return this.edPhi;
    }

    public void setEdPhi(double edPhi) {
	this.edPhi = edPhi;
    }

    @Column(name = "ed_x", nullable = false, precision = 22, scale = 0)
    public double getEdX() {
	return this.edX;
    }

    public void setEdX(double edX) {
	this.edX = edX;
    }

    @Column(name = "ed_y", nullable = false, precision = 22, scale = 0)
    public double getEdY() {
	return this.edY;
    }

    public void setEdY(double edY) {
	this.edY = edY;
    }

    @Column(name = "ed_z", nullable = false, precision = 22, scale = 0)
    public double getEdZ() {
	return this.edZ;
    }

    public void setEdZ(double edZ) {
	this.edZ = edZ;
    }

    @Column(name = "ed_material_cost", nullable = false, precision = 22, scale = 0)
    public double getEdMaterialCost() {
	return this.edMaterialCost;
    }

    public void setEdMaterialCost(double edMaterialCost) {
	this.edMaterialCost = edMaterialCost;
    }

    @Column(name = "ed_labor_cost", nullable = false, precision = 22, scale = 0)
    public double getEdLaborCost() {
	return this.edLaborCost;
    }

    public void setEdLaborCost(double edLaborCost) {
	this.edLaborCost = edLaborCost;
    }

    @Column(name = "ed_equipment_cost", nullable = false, precision = 22, scale = 0)
    public double getEdEquipmentCost() {
	return this.edEquipmentCost;
    }

    public void setEdEquipmentCost(double edEquipmentCost) {
	this.edEquipmentCost = edEquipmentCost;
    }

    @Column(name = "ed_tool_cost", nullable = false, precision = 22, scale = 0)
    public double getEdToolCost() {
	return this.edToolCost;
    }

    public void setEdToolCost(double edToolCost) {
	this.edToolCost = edToolCost;
    }

    @Column(name = "ed_external_cost", nullable = false, precision = 22, scale = 0)
    public double getEdExternalCost() {
	return this.edExternalCost;
    }

    public void setEdExternalCost(double edExternalCost) {
	this.edExternalCost = edExternalCost;
    }

    @Column(name = "ed_price", nullable = false, precision = 22, scale = 0)
    public double getEdPrice() {
	return this.edPrice;
    }

    public void setEdPrice(double edPrice) {
	this.edPrice = edPrice;
    }

    @Column(name = "ed_total_cost", nullable = false, precision = 22, scale = 0)
    public double getEdTotalCost() {
	return this.edTotalCost;
    }

    public void setEdTotalCost(double edTotalCost) {
	this.edTotalCost = edTotalCost;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ed_estimate_id", nullable = false)
    public Estimate getEstimate() {
	return this.estimate;
    }

    public void setEstimate(Estimate estimate) {
	this.estimate = estimate;
    }

    @Override
    public String toString() {
	return "EstimateDetail [edId=" + edId + ", element=" + element + ", estimate=" + estimate + ", material="
		+ material + ", edQuantity=" + edQuantity + ", edMaterialWeight=" + edMaterialWeight + ", edPhi="
		+ edPhi + ", edX=" + edX + ", edY=" + edY + ", edZ=" + edZ + ", edMaterialCost=" + edMaterialCost
		+ ", edLaborCost=" + edLaborCost + ", edEquipmentCost=" + edEquipmentCost + ", edToolCost=" + edToolCost
		+ ", edExternalCost=" + edExternalCost + ", edPrice=" + edPrice + ", edTotalCost=" + edTotalCost + "]";
    }

}
