package com.serp.model;

// Generated Apr 13, 2016 8:57:22 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "function", catalog = "serp")
public class Function implements java.io.Serializable {

	private String functionId;
	private String functionName;
	private String description;
	private Set<Role> roles = new HashSet<Role>(0);

	public Function() {
	}

	public Function(String functionId, String functionName) {
		this.functionId = functionId;
		this.functionName = functionName;
	}

	public Function(String functionId, String functionName, String description,
			Set<Role> roles) {
		this.functionId = functionId;
		this.functionName = functionName;
		this.description = description;
		this.roles = roles;
	}

	@Id
	@Column(name = "function_id", unique = true, nullable = false, length = 50)
	public String getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	@Column(name = "function_name", nullable = false, length = 100)
	public String getFunctionName() {
		return this.functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "functions")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@Override
	public String toString() {
		return "Function [functionId=" + functionId + ", functionName="
				+ functionName + ", description=" + description + "]";
	}

	
}
