package com.serp.model;
// Generated Apr 28, 2016 7:07:22 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LimitInventoryDetail generated by hbm2java
 */
@Entity
@Table(name = "limit_inventory_detail", catalog = "serp")
public class LimitInventoryDetail implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6940647356050510116L;
	private Integer limitInventoryDetailId;
	private Element element;
	private LimitInventory limitInventory;
	private Material material;
	private int quantity;
	private double o;
	private double x;
	private double y;
	private double z;
	private String note;

	public LimitInventoryDetail() {
	}

	public LimitInventoryDetail(Element element, LimitInventory limitInventory, Material material, int quantity,
			double o, double x, double y, double z) {
		this.element = element;
		this.limitInventory = limitInventory;
		this.material = material;
		this.quantity = quantity;
		this.o = o;
		this.x = x;
		this.y = y;
		this.z = z;
	}

	public LimitInventoryDetail(Element element, LimitInventory limitInventory, Material material, int quantity,
			double o, double x, double y, double z, String note) {
		this.element = element;
		this.limitInventory = limitInventory;
		this.material = material;
		this.quantity = quantity;
		this.o = o;
		this.x = x;
		this.y = y;
		this.z = z;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "limit_inventory_detail_id", unique = true, nullable = false)
	public Integer getLimitInventoryDetailId() {
		return this.limitInventoryDetailId;
	}

	public void setLimitInventoryDetailId(Integer limitInventoryDetailId) {
		this.limitInventoryDetailId = limitInventoryDetailId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stock_name", nullable = false)
	public Element getElement() {
		return this.element;
	}

	public void setElement(Element element) {
		this.element = element;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "limit_inventory_id", nullable = false)
	public LimitInventory getLimitInventory() {
		return this.limitInventory;
	}

	public void setLimitInventory(LimitInventory limitInventory) {
		this.limitInventory = limitInventory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "material", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "O", nullable = false, precision = 22, scale = 0)
	public double getO() {
		return this.o;
	}

	public void setO(double o) {
		this.o = o;
	}

	@Column(name = "X", nullable = false, precision = 22, scale = 0)
	public double getX() {
		return this.x;
	}

	public void setX(double x) {
		this.x = x;
	}

	@Column(name = "Y", nullable = false, precision = 22, scale = 0)
	public double getY() {
		return this.y;
	}

	public void setY(double y) {
		this.y = y;
	}

	@Column(name = "Z", nullable = false, precision = 22, scale = 0)
	public double getZ() {
		return this.z;
	}

	public void setZ(double z) {
		this.z = z;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

//	@Override
//	public String toString() {
//		return "LimitInventoryDetail [limitInventoryDetailId=" + limitInventoryDetailId + ", element=" + element
//				+ ", limitInventory=" + limitInventory + ", material=" + material + ", quantity=" + quantity + ", o="
//				+ o + ", x=" + x + ", y=" + y + ", z=" + z + ", note=" + note + "]";
//	}

	
}
