package com.serp.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessingProgramDetail generated by hbm2java
 */
@Entity
@Table(name = "processing_program_detail", catalog = "serp")
public class ProcessingProgramDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2478883061972860670L;
	private Integer id;
	private ProcessingProgram processingProgram;
	private String knife;
	private double parameter1;
	private double parameter2;
	private double parameter3;
	private double parameter4;
	private double regime1;
	private double regime2;
	private double regime3;
	private String programName;
	private Integer theoryTime;
	private Integer realTime;
	private String note;

	public ProcessingProgramDetail() {
	}

	public ProcessingProgramDetail(ProcessingProgram processingProgram, String knife, double parameter1,
			double parameter2, double parameter3, double parameter4, double regime1, double regime2, double regime3) {
		this.processingProgram = processingProgram;
		this.knife = knife;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.regime1 = regime1;
		this.regime2 = regime2;
		this.regime3 = regime3;
	}

	public ProcessingProgramDetail(ProcessingProgram processingProgram, String knife, double parameter1,
			double parameter2, double parameter3, double parameter4, double regime1, double regime2, double regime3,
			String programName, Integer theoryTime, Integer realTime, String note) {
		this.processingProgram = processingProgram;
		this.knife = knife;
		this.parameter1 = parameter1;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.parameter4 = parameter4;
		this.regime1 = regime1;
		this.regime2 = regime2;
		this.regime3 = regime3;
		this.programName = programName;
		this.theoryTime = theoryTime;
		this.realTime = realTime;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "processing_program_id", nullable = false)
	public ProcessingProgram getProcessingProgram() {
		return this.processingProgram;
	}

	public void setProcessingProgram(ProcessingProgram processingProgram) {
		this.processingProgram = processingProgram;
	}

	@Column(name = "knife", nullable = false, length = 50)
	public String getKnife() {
		return this.knife;
	}

	public void setKnife(String knife) {
		this.knife = knife;
	}

	@Column(name = "parameter1", nullable = false, precision = 22, scale = 0)
	public double getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(double parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "parameter2", nullable = false, precision = 22, scale = 0)
	public double getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(double parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", nullable = false, precision = 22, scale = 0)
	public double getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(double parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "parameter4", nullable = false, precision = 22, scale = 0)
	public double getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(double parameter4) {
		this.parameter4 = parameter4;
	}

	@Column(name = "regime1", nullable = false, precision = 22, scale = 0)
	public double getRegime1() {
		return this.regime1;
	}

	public void setRegime1(double regime1) {
		this.regime1 = regime1;
	}

	@Column(name = "regime2", nullable = false, precision = 22, scale = 0)
	public double getRegime2() {
		return this.regime2;
	}

	public void setRegime2(double regime2) {
		this.regime2 = regime2;
	}

	@Column(name = "regime3", nullable = false, precision = 22, scale = 0)
	public double getRegime3() {
		return this.regime3;
	}

	public void setRegime3(double regime3) {
		this.regime3 = regime3;
	}

	@Column(name = "program_name", length = 50)
	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@Column(name = "theory_time")
	public Integer getTheoryTime() {
		return this.theoryTime;
	}

	public void setTheoryTime(Integer theoryTime) {
		this.theoryTime = theoryTime;
	}

	@Column(name = "real_time")
	public Integer getRealTime() {
		return this.realTime;
	}

	public void setRealTime(Integer realTime) {
		this.realTime = realTime;
	}

	@Column(name = "note", length = 250)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
}