package com.serp.model;
// Generated Apr 20, 2016 12:48:52 PM by Hibernate Tools 5.0.0.Alpha3

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.serp.model.Element;
import com.serp.model.ProcessingTechnologyDetail;
import com.serp.model.User;

/**
 * ProcessingTechnology generated by hbm2java
 */
@Entity
@Table(name = "processing_technology", catalog = "serp")
public class ProcessingTechnology implements java.io.Serializable {

	private Integer ptId;
	private Element element;
	private User userByPtCreatorId;
	private User userByPtLeaderAccept;
	private User userByPtManagerAccept;
	private String ptDrawingSymbols;
	private Date ptCreatedDay;
	private Date ptCheckDay;
	private Date ptApproveDay;
	private String ptStatus;
	private String ptNote;
	private Set<ProcessingTechnologyDetail> processingTechnologyDetails = new HashSet<ProcessingTechnologyDetail>(0);

	public ProcessingTechnology() {
	}

	public ProcessingTechnology(Element element, User userByPtCreatorId, User userByPtLeaderAccept,
			User userByPtManagerAccept, String ptDrawingSymbols, Date ptCreatedDay, String ptStatus) {
		this.element = element;
		this.userByPtCreatorId = userByPtCreatorId;
		this.userByPtLeaderAccept = userByPtLeaderAccept;
		this.userByPtManagerAccept = userByPtManagerAccept;
		this.ptDrawingSymbols = ptDrawingSymbols;
		this.ptCreatedDay = ptCreatedDay;
		this.ptStatus = ptStatus;
	}

	public ProcessingTechnology(Element element, User userByPtCreatorId, User userByPtLeaderAccept,
			User userByPtManagerAccept, String ptDrawingSymbols, Date ptCreatedDay, Date ptCheckDay, Date ptApproveDay,
			String ptStatus, String ptNote, Set<ProcessingTechnologyDetail> processingTechnologyDetails) {
		this.element = element;
		this.userByPtCreatorId = userByPtCreatorId;
		this.userByPtLeaderAccept = userByPtLeaderAccept;
		this.userByPtManagerAccept = userByPtManagerAccept;
		this.ptDrawingSymbols = ptDrawingSymbols;
		this.ptCreatedDay = ptCreatedDay;
		this.ptCheckDay = ptCheckDay;
		this.ptApproveDay = ptApproveDay;
		this.ptStatus = ptStatus;
		this.ptNote = ptNote;
		this.processingTechnologyDetails = processingTechnologyDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pt_id", unique = true, nullable = false)
	public Integer getPtId() {
		return this.ptId;
	}

	public void setPtId(Integer ptId) {
		this.ptId = ptId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pt_element_id", nullable = false)
	public Element getElement() {
		return this.element;
	}

	public void setElement(Element element) {
		this.element = element;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pt_creator_id", nullable = false)
	public User getUserByPtCreatorId() {
		return this.userByPtCreatorId;
	}

	public void setUserByPtCreatorId(User userByPtCreatorId) {
		this.userByPtCreatorId = userByPtCreatorId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pt_leader_accept")
	public User getUserByPtLeaderAccept() {
		return this.userByPtLeaderAccept;
	}

	public void setUserByPtLeaderAccept(User userByPtLeaderAccept) {
		this.userByPtLeaderAccept = userByPtLeaderAccept;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pt_manager_accept")
	public User getUserByPtManagerAccept() {
		return this.userByPtManagerAccept;
	}

	public void setUserByPtManagerAccept(User userByPtManagerAccept) {
		this.userByPtManagerAccept = userByPtManagerAccept;
	}

	@Column(name = "pt_drawing_symbols", length = 50)
	public String getPtDrawingSymbols() {
		return this.ptDrawingSymbols;
	}

	public void setPtDrawingSymbols(String ptDrawingSymbols) {
		this.ptDrawingSymbols = ptDrawingSymbols;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pt_created_day", nullable = false, length = 0)
	public Date getPtCreatedDay() {
		return this.ptCreatedDay;
	}

	public void setPtCreatedDay(Date ptCreatedDay) {
		this.ptCreatedDay = ptCreatedDay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pt_check_day", length = 0)
	public Date getPtCheckDay() {
		return this.ptCheckDay;
	}

	public void setPtCheckDay(Date ptCheckDay) {
		this.ptCheckDay = ptCheckDay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pt_approve_day", length = 0)
	public Date getPtApproveDay() {
		return this.ptApproveDay;
	}

	public void setPtApproveDay(Date ptApproveDay) {
		this.ptApproveDay = ptApproveDay;
	}

	@Column(name = "pt_status", nullable = false, length = 20)
	public String getPtStatus() {
		return this.ptStatus;
	}

	public void setPtStatus(String ptStatus) {
		this.ptStatus = ptStatus;
	}

	@Column(name = "pt_note", length = 200)
	public String getPtNote() {
		return this.ptNote;
	}

	public void setPtNote(String ptNote) {
		this.ptNote = ptNote;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "processingTechnology")
	public Set<ProcessingTechnologyDetail> getProcessingTechnologyDetails() {
		return this.processingTechnologyDetails;
	}

	public void setProcessingTechnologyDetails(Set<ProcessingTechnologyDetail> processingTechnologyDetails) {
		this.processingTechnologyDetails = processingTechnologyDetails;
	}

}
