package com.serp.model;
// Generated Apr 20, 2016 12:48:52 PM by Hibernate Tools 5.0.0.Alpha3

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.serp.model.Element;
import com.serp.model.ProcessingProgramDetail;
import com.serp.model.User;

/**
 * ProcessingProgram generated by hbm2java
 */
@Entity
@Table(name = "processing_program", catalog = "serp")
public class ProcessingProgram implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5771831130032906299L;
	private Integer id;
	private Element element;
	private User userByRecieverId;
	private User userByCreatorId;
	private User userByCheckedId;
	private Date creatorDate;
	private Date recieverDate;
	private Date checkedDate;
	private String equipment;
	private String status;
	private String note;
	private String image1;
	private String image2;
	private String image3;
	private String image4;
	private Set<ProcessingProgramDetail> processingProgramDetails = new HashSet<ProcessingProgramDetail>(0);

	public ProcessingProgram() {
	}

	public ProcessingProgram(User userByRecieverId, User userByCreatorId) {
		this.userByRecieverId = userByRecieverId;
		this.userByCreatorId = userByCreatorId;
	}

	public ProcessingProgram(Element element, User userByRecieverId, User userByCreatorId, User userByCheckedId,
			Date creatorDate, Date recieverDate, Date checkedDate, String equipment, String status, String note,
			String image1, String image2, String image3, String image4,
			Set<ProcessingProgramDetail> processingProgramDetails) {
		this.element = element;
		this.userByRecieverId = userByRecieverId;
		this.userByCreatorId = userByCreatorId;
		this.userByCheckedId = userByCheckedId;
		this.creatorDate = creatorDate;
		this.recieverDate = recieverDate;
		this.checkedDate = checkedDate;
		this.equipment = equipment;
		this.status = status;
		this.note = note;
		this.image1 = image1;
		this.image2 = image2;
		this.image3 = image3;
		this.image4 = image4;
		this.processingProgramDetails = processingProgramDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "element_id")
	public Element getElement() {
		return this.element;
	}

	public void setElement(Element element) {
		this.element = element;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reciever_id", nullable = false)
	public User getUserByRecieverId() {
		return this.userByRecieverId;
	}

	public void setUserByRecieverId(User userByRecieverId) {
		this.userByRecieverId = userByRecieverId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "creator_id", nullable = false)
	public User getUserByCreatorId() {
		return this.userByCreatorId;
	}

	public void setUserByCreatorId(User userByCreatorId) {
		this.userByCreatorId = userByCreatorId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "checked_id")
	public User getUserByCheckedId() {
		return this.userByCheckedId;
	}

	public void setUserByCheckedId(User userByCheckedId) {
		this.userByCheckedId = userByCheckedId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creator_date", length = 0)
	public Date getCreatorDate() {
		return this.creatorDate;
	}

	public void setCreatorDate(Date creatorDate) {
		this.creatorDate = creatorDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reciever_date", length = 0)
	public Date getRecieverDate() {
		return this.recieverDate;
	}

	public void setRecieverDate(Date recieverDate) {
		this.recieverDate = recieverDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "checked_date", length = 0)
	public Date getCheckedDate() {
		return this.checkedDate;
	}

	public void setCheckedDate(Date checkedDate) {
		this.checkedDate = checkedDate;
	}

	@Column(name = "equipment", length = 100)
	public String getEquipment() {
		return this.equipment;
	}

	public void setEquipment(String equipment) {
		this.equipment = equipment;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "image1", length = 300)
	public String getImage1() {
		return this.image1;
	}

	public void setImage1(String image1) {
		this.image1 = image1;
	}

	@Column(name = "image2", length = 300)
	public String getImage2() {
		return this.image2;
	}

	public void setImage2(String image2) {
		this.image2 = image2;
	}

	@Column(name = "image3", length = 300)
	public String getImage3() {
		return this.image3;
	}

	public void setImage3(String image3) {
		this.image3 = image3;
	}

	@Column(name = "image4", length = 300)
	public String getImage4() {
		return this.image4;
	}

	public void setImage4(String image4) {
		this.image4 = image4;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processingProgram")
	public Set<ProcessingProgramDetail> getProcessingProgramDetails() {
		return this.processingProgramDetails;
	}

	public void setProcessingProgramDetails(Set<ProcessingProgramDetail> processingProgramDetails) {
		this.processingProgramDetails = processingProgramDetails;
	}
}
