package com.serp.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessingTechnologyDetail generated by hbm2java
 */
@Entity
@Table(name = "processing_technology_detail", catalog = "serp")
public class ProcessingTechnologyDetail implements java.io.Serializable {

	private int id;
	private ProcessingTechnology processingTechnology;
	private String operation;
	private String operationContent;
	private String jig;
	private String operationDrawing;
	private String accessories;
	private String note;

	public ProcessingTechnologyDetail() {
	}

	public ProcessingTechnologyDetail(int id) {
		this.id = id;
	}

	public ProcessingTechnologyDetail(int id, ProcessingTechnology processingTechnology, String operation,
			String operationContent, String jig, String operationDrawing, String accessories, String note) {
		this.id = id;
		this.processingTechnology = processingTechnology;
		this.operation = operation;
		this.operationContent = operationContent;
		this.jig = jig;
		this.operationDrawing = operationDrawing;
		this.accessories = accessories;
		this.note = note;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_processing_technology")
	public ProcessingTechnology getProcessingTechnology() {
		return this.processingTechnology;
	}

	public void setProcessingTechnology(ProcessingTechnology processingTechnology) {
		this.processingTechnology = processingTechnology;
	}

	@Column(name = "operation", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "operation_content", length = 200)
	public String getOperationContent() {
		return this.operationContent;
	}

	public void setOperationContent(String operationContent) {
		this.operationContent = operationContent;
	}

	@Column(name = "jig", length = 50)
	public String getJig() {
		return this.jig;
	}

	public void setJig(String jig) {
		this.jig = jig;
	}

	@Column(name = "operation_drawing", length = 100)
	public String getOperationDrawing() {
		return this.operationDrawing;
	}

	public void setOperationDrawing(String operationDrawing) {
		this.operationDrawing = operationDrawing;
	}

	@Column(name = "accessories", length = 100)
	public String getAccessories() {
		return this.accessories;
	}

	public void setAccessories(String accessories) {
		this.accessories = accessories;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
