package com.serp.model;

// Generated Apr 13, 2016 8:57:22 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Quotationdetails generated by hbm2java
 */
@Entity
@Table(name = "quotationdetails", catalog = "serp")
public class Quotationdetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer quotationDetailsId;
	private Quotation quotation;
	private String nameOfDetail;
	private Integer quantity;
	private String unit;
	private Double price;
	private Double amount;
	private String note;

	public Quotationdetails() {
	}

	public Quotationdetails(Quotation quotation) {
		this.quotation = quotation;
	}

	public Quotationdetails(Quotation quotation, String nameOfDetail,
			Integer quantity, String unit, Double price, Double amount,
			String note) {
		this.quotation = quotation;
		this.nameOfDetail = nameOfDetail;
		this.quantity = quantity;
		this.unit = unit;
		this.price = price;
		this.amount = amount;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QuotationDetailsID", unique = true, nullable = false)
	public Integer getQuotationDetailsId() {
		return this.quotationDetailsId;
	}

	public void setQuotationDetailsId(Integer quotationDetailsId) {
		this.quotationDetailsId = quotationDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QuotationID", nullable = false)
	public Quotation getQuotation() {
		return this.quotation;
	}

	public void setQuotation(Quotation quotation) {
		this.quotation = quotation;
	}

	@Column(name = "NameOfDetail", length = 50)
	public String getNameOfDetail() {
		return this.nameOfDetail;
	}

	public void setNameOfDetail(String nameOfDetail) {
		this.nameOfDetail = nameOfDetail;
	}

	@Column(name = "Quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Unit", length = 50)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "Price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "Amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "Note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
