package com.serp.model;

// Generated Apr 13, 2016 8:57:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quotation generated by hbm2java
 */
@Entity
@Table(name = "quotation", catalog = "serp")
public class Quotation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String quotationId;
	private Estimate estimate;
	private User user;
	private String numOfValidityDays;
	private Integer numOfDaysToComplete;
	private String paymentMethod1;
	private String paymentMethod2;
	private Integer status;
	private Date publishDate;
	private Double amount;
	private Double vat;
	private Double totalAmount;
	private Integer quotationNo;
	private Set<Quotationdetails> quotationdetailses = new HashSet<Quotationdetails>(
			0);

	public Quotation() {
	}

	public Quotation(String quotationId, Estimate estimate) {
		this.quotationId = quotationId;
		this.estimate = estimate;
	}

	public Quotation(String quotationId, Estimate estimate, User user,
			String numOfValidityDays, Integer numOfDaysToComplete,
			String paymentMethod1, String paymentMethod2, Integer status,
			Date publishDate, Double amount, Double vat, Double totalAmount,
			Integer quotationNo, Set<Quotationdetails> quotationdetailses) {
		this.quotationId = quotationId;
		this.estimate = estimate;
		this.user = user;
		this.numOfValidityDays = numOfValidityDays;
		this.numOfDaysToComplete = numOfDaysToComplete;
		this.paymentMethod1 = paymentMethod1;
		this.paymentMethod2 = paymentMethod2;
		this.status = status;
		this.publishDate = publishDate;
		this.amount = amount;
		this.vat = vat;
		this.totalAmount = totalAmount;
		this.quotationNo = quotationNo;
		this.quotationdetailses = quotationdetailses;
	}

	@Id
	@Column(name = "QuotationID", unique = true, nullable = false, length = 50)
	public String getQuotationId() {
		return this.quotationId;
	}

	public void setQuotationId(String quotationId) {
		this.quotationId = quotationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EstimateID", nullable = false)
	public Estimate getEstimate() {
		return this.estimate;
	}

	public void setEstimate(Estimate estimate) {
		this.estimate = estimate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "NumOfValidityDays", length = 50)
	public String getNumOfValidityDays() {
		return this.numOfValidityDays;
	}

	public void setNumOfValidityDays(String numOfValidityDays) {
		this.numOfValidityDays = numOfValidityDays;
	}

	@Column(name = "NumOfDaysToComplete")
	public Integer getNumOfDaysToComplete() {
		return this.numOfDaysToComplete;
	}

	public void setNumOfDaysToComplete(Integer numOfDaysToComplete) {
		this.numOfDaysToComplete = numOfDaysToComplete;
	}

	@Column(name = "PaymentMethod1", length = 50)
	public String getPaymentMethod1() {
		return this.paymentMethod1;
	}

	public void setPaymentMethod1(String paymentMethod1) {
		this.paymentMethod1 = paymentMethod1;
	}

	@Column(name = "PaymentMethod2", length = 55)
	public String getPaymentMethod2() {
		return this.paymentMethod2;
	}

	public void setPaymentMethod2(String paymentMethod2) {
		this.paymentMethod2 = paymentMethod2;
	}

	@Column(name = "Status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PublishDate", length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Column(name = "Amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "VAT", precision = 22, scale = 0)
	public Double getVat() {
		return this.vat;
	}

	public void setVat(Double vat) {
		this.vat = vat;
	}

	@Column(name = "TotalAmount", precision = 22, scale = 0)
	public Double getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "QuotationNo")
	public Integer getQuotationNo() {
		return this.quotationNo;
	}

	public void setQuotationNo(Integer quotationNo) {
		this.quotationNo = quotationNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quotation")
	public Set<Quotationdetails> getQuotationdetailses() {
		return this.quotationdetailses;
	}

	public void setQuotationdetailses(Set<Quotationdetails> quotationdetailses) {
		this.quotationdetailses = quotationdetailses;
	}

}
